services:
    watttheref:
        image: ghcr.io/slaapyhoofd/watttheref:latest
        container_name: watttheref
        restart: unless-stopped
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
            - USER_ID=1000
            - GROUP_ID=1000
            - TZ=Europe/Amsterdam
        volumes:
            - watttheref-data:/app/data

volumes:
    watttheref-data:
